// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_gK5ymBjXKZrn83i4uGWGDlToZtqcGmw',
    appId: '1:400438706418:web:65ebced687e6cfb4a8906b',
    messagingSenderId: '400438706418',
    projectId: 'mini-shop-grocery',
    authDomain: 'mini-shop-grocery.firebaseapp.com',
    storageBucket: 'mini-shop-grocery.firebasestorage.app',
    measurementId: 'G-JWCFSPYYFQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoJr0n1HIgrrcy2JeXq0xFVrSDf3r7650',
    appId: '1:400438706418:ios:d6ad1471e12b5350a8906b',
    messagingSenderId: '400438706418',
    projectId: 'mini-shop-grocery',
    storageBucket: 'mini-shop-grocery.firebasestorage.app',
    iosBundleId: 'com.example.groceryMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_gK5ymBjXKZrn83i4uGWGDlToZtqcGmw',
    appId: '1:400438706418:web:106a4a76adb8f844a8906b',
    messagingSenderId: '400438706418',
    projectId: 'mini-shop-grocery',
    authDomain: 'mini-shop-grocery.firebaseapp.com',
    storageBucket: 'mini-shop-grocery.firebasestorage.app',
    measurementId: 'G-121W8WZF0Y',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoJr0n1HIgrrcy2JeXq0xFVrSDf3r7650',
    appId: '1:400438706418:ios:d6ad1471e12b5350a8906b',
    messagingSenderId: '400438706418',
    projectId: 'mini-shop-grocery',
    storageBucket: 'mini-shop-grocery.firebasestorage.app',
    iosBundleId: 'com.example.groceryMart',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnquEpsDcVNW3i449ut8_kGgES0BUU5KY',
    appId: '1:400438706418:android:2c7934eec8cd4877a8906b',
    messagingSenderId: '400438706418',
    projectId: 'mini-shop-grocery',
    storageBucket: 'mini-shop-grocery.firebasestorage.app',
  );
}
